### ISSUE TITLE
[Bug]: "No appropriate version found." on Community Install

### ISSUE THREAD

**Issue by lumitry** [chrisgrieser/new-tab-default-page#1]
### Bug Description

When attempting to install this plugin in the Community plugin browser, the browser acknowledges that the latest version is v0.5.0, but a toast pops up saying "No appropriate version found." when clicking "Install"

Nothing appears in the dev console that further explains this issue. Additionally, I've tried installation in multiple vaults with varying amounts of plugins and the issue persists.

(I couldn't submit this without clicking the checkmark saying that I updated to the newest version, but to be clear, I have not installed this plugin previously.)

Let me know if there's any more information you need to help track this down!

### Relevant Screenshot

<img width="246" alt="image" src="https://user-images.githubusercontent.com/53492381/190869547-b6aab5f3-8952-4338-a2f2-b734408f582f.png">

### To Reproduce

1. Open Obsidian Community Plugins browser
2. Find the "New Tab Default Page" plugin
3. Click install
4. Observe error

### Obsidian Version

0.15.9

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Hi, that is not a bug - the plugin is made for Obsidian 0.16, which is currently still in beta. You need an Obsidian Insider License to install 0.16 right now, or wait a bit until 0.16 is publicly released 🙂
