### ISSUE TITLE
"Plugin for the New Tab Page is not enabled." even though plugin is enabled

### ISSUE THREAD

**Issue by tim-hilde** [chrisgrieser/new-tab-default-page#11]
### Bug Description

Since updating to Another Quick Switcher 8.4.1 I get the error message `Plugin for the New Tab Page is not enabled.` AQS is enabled of course.

### Obsidian Version

v1.1.12

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
?

**Comment by tim-hilde** [comment]
Oops, accidentally closed the issue.

**Comment by chrisgrieser** [comment]
fixed in latest release

**Comment by chrisgrieser** [comment]
@Kani3D That problem can arise when you deleted or rename the default search command from another quick switcher, since then the command can't be found. 

Try restoring the default, and if that does not work please open a new bug report.
