### ISSUE TITLE
[Bug]: "layout-change" event interferes with plugins that trigger new views

### ISSUE THREAD

**Issue by Acylation** [chrisgrieser/new-tab-default-page#14]
### Bug Description

Users of [Projects](https://github.com/marcusolsson/obsidian-projects) plugin reported a [bug](https://github.com/marcusolsson/obsidian-projects/issues/552) recently.  In brief, if we set a  markdown note as the default new tab page, when we clicking on the ribbon icon of the `Projects` plugin that tends to open a new view, we will get the default new page, rather than the `Projects` view.

This plugin registers "layout-change" event to observe the changes to the leaves.
```ts
  this.registerEvent(
  app.workspace.on("layout-change", () => {
	  this.checkForNewTab(existingLeaves);
  }));
```

While the `Projects` plugin will create a own view when clicking on its ribbon icon
```ts
  this.addRibbonIcon("layout", "Open projects", () => {
    this.activateView();
  });
```

```ts
  async activateView(projectId?: ProjectId, viewId?: ViewId): Promise<void> {
    const leaf = await this.getOrCreateLeaf();

    leaf.setViewState({
      type: VIEW_TYPE_PROJECTS,
      state: {
        projectId,
        viewId,
      },
    });

    this.app.workspace.revealLeaf(leaf);
  }

```

### Relevant Screenshot

https://user-images.githubusercontent.com/73122375/236517104-b3782d75-2c36-4c93-9d36-d9768f9b8d80.mp4

### To Reproduce

1. Install `Projects` plugin and enable
2. Make sure the default new tab page is configured as a valid file or note
3. Clicking on the `Projects` ribbon icon
4. Turn off this plugin, and click on the `Projects` ribbon icon again to see the difference

### Obsidian Version

1.2.7

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by joriswvanrijn** [comment]
I ran into this issue as well. I've created a PR for this issue: https://github.com/chrisgrieser/new-tab-default-page/pull/18

**Comment by chrisgrieser** [comment]
closed via #18

**Comment by joriswvanrijn** [comment]
After some usage, I'm noticing that it alters other behavior as well. It seems that this fix breaks opening new tabs on the homepage when a tab is already open.

In this plugin it seems to work: https://github.com/olrenso/obsidian-home-tab/blob/main/src/main.ts#L161

I'll create an updated PR when I find the time later this week!

**Comment by joriswvanrijn** [comment]
New PR: https://github.com/chrisgrieser/new-tab-default-page/pull/19
