### ISSUE TITLE
Opening a note in a new tab via AQS opens AWS again

### ISSUE THREAD

**Issue by tim-hilde** [chrisgrieser/new-tab-default-page#2]
### Bug Description

When I open a new note in a new tab via AQS the modal is opened again.

### Relevant Screenshot

https://user-images.githubusercontent.com/44113468/192491783-1bc608ce-b714-4176-8e53-4164e7ff8b12.mov

### To Reproduce

1. Open AQS
2. Open a note in new tab
3. AQS is opened 

### Obsidian Version

0.16.3

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thanks, fixed!
