### ISSUE TITLE
[Bug]: 1.4.2 New Tab Wont Trigger

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [chrisgrieser/new-tab-default-page#20]
### Bug Description

The plugin appears to have stopped working as of 1.4.2. Tested on multiple vaults with a combination of 0 to many other plugins and the default new tab widow just opens by default now. 

### Obsidian Version

1.4.2

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
@joriswvanrijn My guess is that it's not the obsidian version, but rather the plugin version, and potentially related to your latest PR(s)?

**Comment by joriswvanrijn** [comment]
Hmm, could definitely be. 

@ObsidianTTRPGProject  Which platform are you using? Is it possible to confirm that the previous version is working? 

@chrisgrieser did i by any chance make a mistake in the default setting which prevents the plug-in from loading?

It’s unfortunate, but I have a 2 week holiday without access to my dev laptop. Maybe we should revert the PR and I’ll test it better when I get back.

**Comment by chrisgrieser** [comment]
not sure, I am on the latest version, and it works fine for me?

**Comment by chrisgrieser** [comment]
oh wait, I haven't made a new release after your second PR, @joriswvanrijn, which could be the issue.

@ObsidianTTRPGProject I just released 0.11.2, which potentially fixes the issue. Could you update and give it a try?

**Comment by joriswvanrijn** [comment]
Check! Hope that fixes it.

I just checked for obsidian version 1.4.12 and can confirm it works as well.

@chrisgrieser did this plugin work on mobile before? I haven't considered that in my PR.

**Comment by ObsidianTTRPGProject** [comment]
Using the Desktop version with Windows 11. I'm not near the pc right now but will report back.

**Comment by ObsidianTTRPGProject** [comment]
Ok updated and everything is working again :) thanks guys.
