### ISSUE TITLE
[Spelling]: Compatability → Compatibility 

### ISSUE THREAD

**Issue by kepano** [chrisgrieser/new-tab-default-page#21]
### Bug Description

Spelling error: "Compatability mode" should be "Compatibility mode"

Also note that Settings in Obsidian should use sentence case :)

### Obsidian Version

1.4.16

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
fixed.

> Also note that Settings in Obsidian should use sentence case :)

At the time the plugin was written, there was no such guideline yet :P 
(also fixed)
