### ISSUE TITLE
Ability to open a canvas on a new tab. 

### ISSUE THREAD

**Issue by daxmonson** [chrisgrieser/new-tab-default-page#22]
### Feature Requested

Finding this would be a very useful addition for things like a zoomable dashboard with buttons on a new tab. 

### Checklist

- [ ] The feature would be useful to more users than just me.

**Comment by nifanle7** [comment]
It supports canvas by adding file suffix of ".canvas"

**Comment by chrisgrieser** [comment]
Closing this since already supported 🙂

**Comment by daxmonson** [comment]
Ahh, a suffix for that and a welcome Easter egg. Thanks for your work, donating now.
