### ISSUE TITLE
Feature Request: Open Periodic Notes daily notes

### ISSUE THREAD

**Issue by Claw76** [chrisgrieser/new-tab-default-page#5]
### Feature Requested

dbc087479cedf69b963a88b17840ed3c5f81a5b4 does not include opening **daily** notes via Periodic Notes.
It would be great if there was an option for that as well.  

**Reason**: 
Periodic Notes has more customization options regarding the folder/subfolder where the daily note is created.  
The core Daily Notes plugin does not support these customizations so you cannot use it to open daily notes created by the Periodic Notes plugin.

The change/addition would be very small:
```js
.addOption("periodic-notes:open-daily-note", "Daily Note (Periodic Notes Plugin")
```

### Relevant Screenshot

**Periodic Notes customization options** (the core Daily Notes plugin cannot open this):
![image](https://user-images.githubusercontent.com/49340713/195820281-4c4169b3-c5d5-486e-9ee9-c49855c385cc.png)

**How the dropdown would look**:
![image](https://user-images.githubusercontent.com/49340713/195819343-486f8911-33c1-4ddd-80e1-c83c26c95b69.png)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Ah, I see. Added in version 0.9.1.
