### ISSUE TITLE
Feature Request: Compatibility with mobile

### ISSUE THREAD

**Issue by anvimea** [chrisgrieser/new-tab-default-page#6]
### Feature Requested

Great plugin, as the title states I was wondering if you had any future plans to create mobile compatibility, as the plugin doesn't currently support my iPhone at least. 

I think it'd be even more useful for mobile users than desktop users.

### Relevant Screenshot

<img width="375" alt="image" src="https://user-images.githubusercontent.com/20266830/195985268-1c2a026c-44a9-4729-a9b0-46289d6985f2.png">

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I don't use obsidian on mobile myself, but it should theoretically work on mobile I think. 

Could someone test by changing the `isDesktopOnly` key in `the manifest.json` to false and see whether it works on mobile?

**Comment by Lisandra-dev** [comment]
I tryed to change this key and the plugin works fine ! I think it will be good to update the manifest to includes mobile :)

**Comment by chrisgrieser** [comment]
all right, enabled mobile support in the manifest!
