### ISSUE TITLE
[Bug]: can't change the new page path

### ISSUE THREAD

**Issue by jbergenudd** [chrisgrieser/new-tab-default-page#8]
### Bug Description

just installed.
new tab opens... is: new tab page 
Default new tab page: Meta/Homepage.md

when i try to change the path nothing happens. can't write, can't select in the text field

 using 0.10.0 of the plugin

### To Reproduce

nothing other than what's described in the description

### Obsidian Version

1.0.3

### Which editor are you using?

- [X] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by jbergenudd** [comment]
the plugin does not open Meta/Homepage.md even if it exists

**Comment by chrisgrieser** [comment]
You mean the text field in the settings does not work? Could you maybe make a short video recording of how that looks?

**Comment by jbergenudd** [comment]
nevermind. it worked when i tried to record (and I can't recreate it now). perhaps the plugin just needed to reload or something...
